set -g mouse on
set -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
##### Status bar arriba, minimal, warm #####
set -g status-position top
set -g status on
set -g status-interval 5
set -g status-justify left

# Fondo "default" para que use el de Alacritty (tu #1F1D1A)
set -g status-style bg=default,fg=colour252

# Longitudes
set -g status-left-length 40
set -g status-right-length 80

# Left: sesión, discreto
set -g status-left "#[fg=colour250]#S#[fg=colour240] · "

# Windows: tabs suaves (sin bloques)
set -g window-status-style fg=colour245,bg=default
set -g window-status-current-style fg=colour230,bg=default

set -g window-status-format " #I:#W "
set -g window-status-current-format "#[bold] #I:#W "

# Right: host + hora, ultra simple
set -g status-right "#[fg=colour240]#H #[fg=colour239]· #[fg=colour245]%H:%M "

##### Separadores / bordes de panes (suaves, no chillones) #####
set -g pane-border-style fg=colour237
set -g pane-active-border-style fg=colour250

##### Mensajes / command line (no flashbang) #####
set -g message-style bg=default,fg=colour252
set -g message-command-style bg=default,fg=colour252

# Status de 2 lines
set -g status-position top
set -g status 2

# línea 2: separador full width (string largo, tmux lo recorta al ancho)
set -g status-format[1] "#[fg=colour238]────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────"

##### Plugins #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @smart-splits_move_left_key 'C-h'
set -g @smart-splits_move_down_key 'C-j'
set -g @smart-splits_move_up_key 'C-k'
set -g @smart-splits_move_right_key 'C-l'
set -g @smart-splits_resize_left_key 'M-h'
set -g @smart-splits_resize_down_key 'M-j'
set -g @smart-splits_resize_up_key 'M-k'
set -g @smart-splits_resize_right_key 'M-l'
set -g @smart-splits_resize_step_size '3'

# autosave cada 15 min
set -g @continuum-save-interval '5'

# restaurar al arrancar tmux
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'

# Binds
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
