set -g mouse on
##### Status bar arriba, minimal, warm #####
set -g status-position top
set -g status on
set -g status-interval 5
set -g status-justify left

# Fondo "default" para que use el de Alacritty (tu #1F1D1A)
set -g status-style bg=default,fg=colour252

# Longitudes
set -g status-left-length 40
set -g status-right-length 80

# Left: sesión, discreto
set -g status-left "#[fg=colour250]#S#[fg=colour240] · "

# Windows: tabs suaves (sin bloques)
set -g window-status-style fg=colour245,bg=default
set -g window-status-current-style fg=colour230,bg=default

set -g window-status-format " #I:#W "
set -g window-status-current-format "#[bold] #I:#W "

# Right: host + hora, ultra simple
set -g status-right "#[fg=colour240]#H #[fg=colour239]· #[fg=colour245]%H:%M "

##### Separadores / bordes de panes (suaves, no chillones) #####
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour244

##### Mensajes / command line (no flashbang) #####
set -g message-style bg=default,fg=colour252
set -g message-command-style bg=default,fg=colour252

# Status de 2 lines
set -g status-position top
set -g status 2

# línea 2: separador full width (string largo, tmux lo recorta al ancho)
set -g status-format[1] "#[fg=colour238]────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────"

##### Plugins #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# autosave cada 15 min
set -g @continuum-save-interval '5'

# restaurar al arrancar tmux
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
